<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<Version>1.0.0</Version>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Extensions\Dtos\NovaPasta1\**" />
    <Compile Remove="Extensions\Dtos\NovaPasta\**" />
    <Content Remove="Extensions\Dtos\NovaPasta1\**" />
    <Content Remove="Extensions\Dtos\NovaPasta\**" />
    <EmbeddedResource Remove="Extensions\Dtos\NovaPasta1\**" />
    <EmbeddedResource Remove="Extensions\Dtos\NovaPasta\**" />
    <None Remove="Extensions\Dtos\NovaPasta1\**" />
    <None Remove="Extensions\Dtos\NovaPasta\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.17.0" />
    <PackageReference Include="MySql.Data" Version="9.6.0" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="Quartz" Version="3.18.0" />
    <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.18.0" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.0" />
    <PackageReference Include="Quartz.Serialization.Json" Version="3.18.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
  </ItemGroup>

  <ItemGroup>
	<Content Include="config\**\*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

    <ItemGroup>
	    <Content Update="EmailTemplates/*.html" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    </ItemGroup>
</Project>
